apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-producer
  name: udaconnect-locations-producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: udaconnect-locations-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-producer
  name: udaconnect-locations-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-producer
  template:
    metadata:
      labels:
        service: udaconnect-locations-producer
    spec:
     containers:
     - image: mmsaad85/udaconnect-locations-producer:1.0.7
       name: udaconnect-locations-producer
       imagePullPolicy: Always
     restartPolicy: Always
