---
swagger: "2.0"
info:
  version: 0.1.0
  title: UdaConnect API
basePath: /
tags:
- name: UdaConnect
  description: Connections via geolocation.
consumes:
- application/json
produces:
- application/json
paths:
  /api/locations/{location_id}:
    get:
      tags:
      - UdaConnect
      operationId: get_location_resource
      parameters:
      - name: location_id
        in: path
        description: Unique ID for a given Location
        required: true
        type: string
      responses:
        "200":
          description: Success
definitions: {}
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
